@extends('admin.layout')
@section('title', 'Refunds')
@section('content')
<div class="mb-7"><p class="text-sm font-semibold uppercase tracking-[0.18em] text-indigo-600">Customer returns</p><h1 class="mt-1 text-3xl font-bold text-slate-950">Refunds</h1><p class="mt-2 text-sm text-slate-500">Return received funds while preserving the original ledger entry.</p></div>
@include('admin.finance._nav')
<div class="grid gap-6 xl:grid-cols-3"><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm xl:col-span-2" data-testid="finance-refunds-list"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100"><thead class="bg-slate-50"><tr>@foreach(['Refund','Date','Account','Amount','Reason','Status'] as $h)<th class="px-5 py-3 text-left text-xs font-semibold uppercase text-slate-500">{{ $h }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">@forelse($refunds as $refund)<tr><td class="px-5 py-4 font-semibold">{{ $refund->number }}</td><td class="px-5 py-4 text-sm">{{ $refund->refunded_at->format('M j, Y') }}</td><td class="px-5 py-4 text-sm">{{ $refund->account?->name }}</td><td class="px-5 py-4 text-sm font-bold text-rose-600">{{ format_money($refund->amount,2,$refund->currency) }}</td><td class="px-5 py-4 text-sm">{{ $refund->reason }}</td><td class="px-5 py-4 text-sm capitalize">{{ $refund->status }}</td></tr>@empty<tr><td colspan="6" class="px-6 py-14 text-center text-sm text-slate-500">No refunds.</td></tr>@endforelse</tbody></table></div></section>
@if(app(\App\Shared\Authorization\ModuleAuthorizer::class)->allows('finance', \App\Finance\Enums\FinanceAbility::REFUND))<aside class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">Issue refund</h2><form method="POST" action="{{ route('admin.finance.refunds.store') }}" class="mt-5 space-y-4" data-testid="finance-refund-form">@csrf
<div><label class="mb-1 block text-sm font-semibold">Paid invoice</label><select name="invoice_public_id" required class="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">Select invoice</option>@foreach($invoices as $invoice)<option value="{{ $invoice->public_id }}">{{ $invoice->number }} · {{ $invoice->customer_name }} · {{ format_money($invoice->paid_amount,2,$invoice->currency) }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm font-semibold">Account</label><select name="account_id" required class="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} · {{ $account->currency }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm font-semibold">Amount</label><input type="number" step="0.0001" min="0.0001" name="amount" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-sm font-semibold">Reason</label><input name="reason" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div>
<div><label class="mb-1 block text-sm font-semibold">Reference</label><input name="reference" class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div>
<button class="w-full rounded-xl bg-rose-600 px-5 py-3 text-sm font-bold text-white">Complete refund</button></form></aside>@endif</div>
@endsection
