@extends('admin.layout')
@section('title', 'Payments')
@section('content')
<div class="mb-7"><p class="text-sm font-semibold uppercase tracking-[0.18em] text-indigo-600">Cash movement</p><h1 class="mt-1 text-3xl font-bold text-slate-950">Payments</h1><p class="mt-2 text-sm text-slate-500">Record partial or full payments and allocate them to invoices or approved bills.</p></div>
@include('admin.finance._nav')
<div class="grid gap-6 xl:grid-cols-3">
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm xl:col-span-2" data-testid="finance-payments-list"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100"><thead class="bg-slate-50"><tr>@foreach(['Payment','Date','Account','Direction','Amount','Method'] as $h)<th class="px-5 py-3 text-left text-xs font-semibold uppercase text-slate-500">{{ $h }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-100">@forelse($payments as $payment)<tr><td class="px-5 py-4 font-semibold">{{ $payment->number }}</td><td class="px-5 py-4 text-sm">{{ $payment->payment_date->format('M j, Y') }}</td><td class="px-5 py-4 text-sm">{{ $payment->account?->name }}</td><td class="px-5 py-4 text-sm capitalize">{{ $payment->direction }}</td><td class="px-5 py-4 text-sm font-bold">{{ format_money($payment->amount, 2, $payment->currency) }}</td><td class="px-5 py-4 text-sm capitalize">{{ str_replace('_',' ',$payment->method) }}</td></tr>@empty<tr><td colspan="6" class="px-6 py-14 text-center text-sm text-slate-500">No payments recorded.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $payments->links() }}</div></section>
@if(app(\App\Shared\Authorization\ModuleAuthorizer::class)->allows('finance', \App\Finance\Enums\FinanceAbility::PAY))
<aside class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">Record payment</h2><form method="POST" action="{{ route('admin.finance.payments.store') }}" class="mt-5 space-y-4" data-testid="finance-payment-form">@csrf
<div><label class="mb-1 block text-sm font-semibold">Document</label><select name="document_selector" required data-document-selector class="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">Select invoice or bill</option><optgroup label="Invoices">@foreach($invoices as $invoice)<option value="invoice|{{ $invoice->public_id }}">Invoice {{ $invoice->number }} · {{ $invoice->customer_name }}</option>@endforeach</optgroup><optgroup label="Approved bills">@foreach($bills as $bill)<option value="bill|{{ $bill->public_id }}">Bill {{ $bill->number }} · {{ $bill->vendor?->name }}</option>@endforeach</optgroup></select><input type="hidden" name="document_type" data-document-type><input type="hidden" name="document_public_id" data-document-id></div>
<div><label class="mb-1 block text-sm font-semibold">Account</label><select name="account_id" required class="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} · {{ $account->currency }}</option>@endforeach</select></div>
<div class="grid grid-cols-2 gap-3"><div><label class="mb-1 block text-sm font-semibold">Amount</label><input type="number" step="0.0001" min="0.0001" name="amount" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div><div><label class="mb-1 block text-sm font-semibold">Date</label><input type="date" name="payment_date" value="{{ today()->toDateString() }}" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div></div>
<div><label class="mb-1 block text-sm font-semibold">Method</label><select name="method" class="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach(['bank_transfer','cash','card','gateway','cheque','other'] as $method)<option value="{{ $method }}">{{ ucfirst(str_replace('_',' ',$method)) }}</option>@endforeach</select></div>
<div><label class="mb-1 block text-sm font-semibold">Reference</label><input name="reference" class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div>
<button class="w-full rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white">Record payment</button></form></aside>
@endif
</div>
@push('scripts')<script>document.querySelector('[data-document-selector]')?.addEventListener('change',event=>{const [type,id]=event.target.value.split('|');document.querySelector('[data-document-type]').value=type||'';document.querySelector('[data-document-id]').value=id||'';});</script>@endpush
@endsection
