@extends('admin.layout')
@section('title', 'Finance Reports')
@section('content')
<div class="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold uppercase tracking-[0.18em] text-indigo-600">Financial intelligence</p><h1 class="mt-1 text-3xl font-bold text-slate-950">Finance reports</h1><p class="mt-2 text-sm text-slate-500">Profitability, aging, cash flow and budget performance.</p></div><form method="GET"><select name="currency" onchange="this.form.submit()" class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold">@foreach($availableCurrencies as $available)<option value="{{ $available }}" @selected($currency===$available)>{{ $available }}</option>@endforeach</select></form></div>
@include('admin.finance._nav')
<section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3" data-testid="finance-report-metrics">@foreach([['Invoiced',$summary['invoiced'],'indigo'],['Received',$summary['received'],'emerald'],['Vendor bills',$summary['billed'],'amber'],['Paid bills',$summary['paid'],'rose'],['Refunded',$summary['refunded'],'violet'],['Profit / loss',$summary['profit_loss'],'slate']] as [$label,$value,$tone])<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-semibold text-slate-500">{{ $label }}</p><p class="mt-3 text-2xl font-bold text-slate-900">{{ format_money($value,2,$currency) }}</p></article>@endforeach</section>
<div class="mt-6 grid gap-6 lg:grid-cols-2">@foreach([['Receivables aging',$receivablesAging],['Payables aging',$payablesAging]] as [$title,$aging])<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">{{ $title }}</h2><div class="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">@foreach(['not_due'=>'Not due','1_30'=>'1–30','31_60'=>'31–60','61_90'=>'61–90','over_90'=>'90+'] as $key=>$label)<div class="rounded-xl bg-slate-50 p-3"><p class="text-xs font-semibold text-slate-500">{{ $label }}</p><p class="mt-2 text-sm font-bold">{{ format_money($aging[$key],2,$currency) }}</p></div>@endforeach</div></section>@endforeach</div>
<div class="mt-6 grid gap-6 lg:grid-cols-2"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">Monthly cash flow</h2><div class="mt-4 space-y-3">@forelse($cashFlow as $month=>$flow)<div class="grid grid-cols-3 gap-3 rounded-xl bg-slate-50 p-3 text-sm"><span class="font-semibold">{{ $month }}</span><span class="text-emerald-600">+{{ format_money($flow['incoming'],2,$currency) }}</span><span class="text-rose-600">−{{ format_money($flow['outgoing'],2,$currency) }}</span></div>@empty<p class="py-8 text-center text-sm text-slate-500">No cash flow data.</p>@endforelse</div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">Budget performance</h2><div class="mt-4 space-y-3">@forelse($budgetPerformance as $item)<div class="rounded-xl bg-slate-50 p-3"><div class="flex justify-between text-sm"><span class="font-semibold">{{ $item['budget']->name }}</span><span class="font-bold">{{ $item['summary']['utilization_percent'] }}%</span></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-white"><div class="h-full bg-indigo-500" style="width:{{ min(100,$item['summary']['utilization_percent']) }}%"></div></div></div>@empty<p class="py-8 text-center text-sm text-slate-500">No budgets in {{ $currency }}.</p>@endforelse</div></section></div>
@endsection
