@extends('admin.layout')

@section('title', $submission->reference_number ?: 'Submission')

@section('content')
<div class="space-y-6" data-testid="submission-detail">
    <div class="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-4">
        <div><p class="font-mono text-sm text-indigo-600">{{ $submission->reference_number ?: 'Draft' }}</p><h2 class="text-3xl font-bold text-slate-900">{{ $submission->title }}</h2><p class="mt-1 text-slate-500">{{ $submission->type->name }} · {{ $submission->applicant->email ?? 'Unknown applicant' }}</p></div>
        <div class="flex flex-wrap gap-2">@if($submission->is_selected)<form method="POST" action="{{ route('admin.submissions.convert', $submission) }}">@csrf<button class="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Convert to speaker</button></form>@endif<a href="{{ route('admin.submissions.index') }}" class="rounded-xl border bg-white px-4 py-2 text-sm font-semibold">Back</a></div>
    </div>
    <div class="grid xl:grid-cols-[1fr_22rem] gap-6">
        <div class="space-y-6">
            <section class="rounded-2xl border bg-white p-6 shadow-sm"><h3 class="text-lg font-bold">Submission answers</h3><div class="mt-4 grid md:grid-cols-2 gap-4">@forelse($submission->answers as $answer)<div class="rounded-xl bg-slate-50 p-4"><p class="text-xs font-semibold uppercase text-slate-500">{{ $answer->question_label }}</p><div class="mt-2 text-sm text-slate-800">{{ $answer->answer_text ?? collect($answer->answer_json)->join(', ') ?: '—' }}</div></div>@empty<p class="text-slate-500">No answers saved.</p>@endforelse</div></section>
            <section class="rounded-2xl border bg-white p-6 shadow-sm"><h3 class="text-lg font-bold">Reviews</h3><div class="mt-4 space-y-3">@forelse($submission->reviews as $review)<div class="flex flex-col sm:flex-row sm:items-center justify-between gap-2 rounded-xl border p-4"><div><p class="font-semibold">{{ $review->reviewer->name }}</p><p class="text-sm text-slate-500">{{ $review->recommendation ?: 'No recommendation' }}</p></div><div class="text-2xl font-bold text-indigo-600">{{ number_format($review->normalized_score, 1) }}</div></div>@empty<p class="text-slate-500">No completed reviews.</p>@endforelse</div></section>
            <section class="rounded-2xl border bg-white p-6 shadow-sm"><h3 class="text-lg font-bold">Activity</h3><div class="mt-4 space-y-3">@foreach($submission->activities->take(20) as $activity)<div class="border-l-2 border-indigo-200 pl-4"><p class="text-sm font-medium">{{ str_replace(['.', '_'], ' ', $activity->type) }}</p><p class="text-xs text-slate-500">{{ $activity->created_at->diffForHumans() }}</p></div>@endforeach</div></section>
        </div>
        <aside class="space-y-5">
            <section class="rounded-2xl border bg-white p-5 shadow-sm"><h3 class="font-bold">Assign reviewer</h3><form method="POST" action="{{ route('admin.submissions.reviewers.assign', $submission) }}" class="mt-4 space-y-3">@csrf<select name="reviewer_id" required class="w-full rounded-xl border-slate-300"><option value="">Choose reviewer</option>@foreach($reviewers as $reviewer)<option value="{{ $reviewer->id }}">{{ $reviewer->name }} · {{ $reviewer->assignments()->whereIn('status',['assigned','accepted','in_progress'])->count() }}/{{ $reviewer->capacity ?: '∞' }}</option>@endforeach</select><input type="date" name="due_at" class="w-full rounded-xl border-slate-300"><button class="w-full rounded-xl border border-indigo-200 px-4 py-2 font-semibold text-indigo-700">Assign review</button></form></section>
            <section class="rounded-2xl border bg-white p-5 shadow-sm"><h3 class="font-bold">Workflow</h3><p class="mt-2 text-sm text-slate-500">Current stage</p><p class="text-lg font-bold">{{ $submission->currentStage->name ?? ucfirst($submission->status->value) }}</p><form method="POST" action="{{ route('admin.submissions.stage', $submission) }}" class="mt-4 space-y-3">@csrf<select name="stage_id" class="w-full rounded-xl border-slate-300">@foreach($availableStages as $stage)<option value="{{ $stage->id }}" @selected($submission->current_stage_id === $stage->id)>{{ $stage->name }}</option>@endforeach</select><textarea name="note" placeholder="Transition note" class="w-full rounded-xl border-slate-300 text-sm"></textarea><button class="w-full rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white">Change stage</button></form></section>
            <section class="rounded-2xl border bg-white p-5 shadow-sm"><h3 class="font-bold">Decision</h3><form method="POST" action="{{ route('admin.submissions.decision', $submission) }}" class="mt-4 space-y-3">@csrf<select name="decision" class="w-full rounded-xl border-slate-300">@foreach(['selected','conditionally_selected','waitlisted','revision_required','rejected','disqualified'] as $decision)<option>{{ $decision }}</option>@endforeach</select><textarea name="reason" placeholder="Decision reason" class="w-full rounded-xl border-slate-300 text-sm"></textarea><button class="w-full rounded-xl bg-indigo-600 px-4 py-2 font-semibold text-white">Record decision</button></form></section>
            <section class="rounded-2xl border bg-white p-5 shadow-sm"><h3 class="font-bold">Request revision</h3><form method="POST" action="{{ route('admin.submissions.revision', $submission) }}" class="mt-4 space-y-3">@csrf<input type="date" name="deadline" required class="w-full rounded-xl border-slate-300"><textarea name="instructions" required placeholder="Revision instructions" class="w-full rounded-xl border-slate-300 text-sm"></textarea><button class="w-full rounded-xl border border-indigo-200 px-4 py-2 font-semibold text-indigo-700">Send request</button></form></section>
        </aside>
    </div>
</div>
@endsection
