@extends('admin.layout')
@section('title', 'Vendor Bills')
@section('content')
<div class="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold uppercase tracking-[0.18em] text-indigo-600">Payables</p><h1 class="mt-1 text-3xl font-bold tracking-tight text-slate-950">Vendor bills</h1><p class="mt-2 text-sm text-slate-500">Track approved obligations separately from their payments.</p></div>@if(app(\App\Shared\Authorization\ModuleAuthorizer::class)->allows('finance', \App\Finance\Enums\FinanceAbility::MANAGE_EXPENSES))<a href="{{ route('admin.finance.bills.create') }}" class="rounded-xl bg-indigo-600 px-5 py-3 text-center text-sm font-bold text-white">New bill</a>@endif</div>
@include('admin.finance._nav')
<section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm" data-testid="finance-bills-list"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100">
<thead class="bg-slate-50"><tr>@foreach(['Bill', 'Vendor', 'Due', 'Total', 'Outstanding', 'Approval', 'Payment', ''] as $heading)<th class="px-5 py-3 text-left text-xs font-semibold uppercase text-slate-500">{{ $heading }}</th>@endforeach</tr></thead>
<tbody class="divide-y divide-slate-100">@forelse($bills as $bill)<tr><td class="px-5 py-4 font-semibold text-slate-900">{{ $bill->number }}</td><td class="px-5 py-4 text-sm text-slate-600">{{ $bill->vendor?->name }}</td><td class="px-5 py-4 text-sm text-slate-600">{{ $bill->due_date?->format('M j, Y') ?: '—' }}</td><td class="px-5 py-4 text-sm font-bold">{{ format_money($bill->total_amount, 2, $bill->currency) }}</td><td class="px-5 py-4 text-sm font-bold text-amber-700">{{ format_money(bcsub($bill->total_amount, $bill->paid_amount, 4), 2, $bill->currency) }}</td><td class="px-5 py-4 text-sm capitalize">{{ str_replace('_', ' ', $bill->approval_status) }}</td><td class="px-5 py-4 text-sm capitalize">{{ str_replace('_', ' ', $bill->payment_status) }}</td><td class="px-5 py-4">@if($bill->approval_status === 'draft' && app(\App\Shared\Authorization\ModuleAuthorizer::class)->allows('finance', \App\Finance\Enums\FinanceAbility::MANAGE_EXPENSES))<form method="POST" action="{{ route('admin.finance.approvals.bills.submit', $bill) }}">@csrf<button class="text-xs font-bold text-indigo-600">Submit</button></form>@endif</td></tr>@empty<tr><td colspan="8" class="px-6 py-14 text-center text-sm text-slate-500">No vendor bills.</td></tr>@endforelse</tbody>
</table></div></section><div class="mt-6">{{ $bills->links() }}</div>
@endsection
