@extends('admin.layout')
@section('title', 'Budgets')
@section('content')
<div class="mb-7"><p class="text-sm font-semibold uppercase tracking-[0.18em] text-indigo-600">Financial planning</p><h1 class="mt-1 text-3xl font-bold text-slate-950">Budgets</h1><p class="mt-2 text-sm text-slate-500">Compare planned spend with approved commitments and actual payments.</p></div>
@include('admin.finance._nav')
<div class="grid gap-6 xl:grid-cols-3"><section class="grid gap-4 sm:grid-cols-2 xl:col-span-2" data-testid="finance-budgets-list">@forelse($budgets as $budget)@php($summary=$budget->summary)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold uppercase text-indigo-600">{{ $budget->number }}</p><h2 class="mt-1 font-bold text-slate-900">{{ $budget->name }}</h2></div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize">{{ $budget->type }}</span></div><div class="mt-5 flex items-end justify-between"><div><p class="text-xs text-slate-500">Committed / planned</p><p class="mt-1 font-bold">{{ format_money($summary['committed_expense'],2,$budget->currency) }} <span class="font-normal text-slate-400">/ {{ format_money($budget->planned_expense,2,$budget->currency) }}</span></p></div><p class="text-2xl font-bold {{ $summary['utilization_percent'] > 100 ? 'text-rose-600' : 'text-indigo-600' }}">{{ $summary['utilization_percent'] }}%</p></div><div class="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full {{ $summary['utilization_percent'] > 100 ? 'bg-rose-500' : ($summary['utilization_percent'] >= $budget->critical_threshold ? 'bg-amber-500' : 'bg-indigo-500') }}" style="width: {{ min(100,$summary['utilization_percent']) }}%"></div></div><p class="mt-4 text-xs text-slate-500">{{ $budget->period_start->format('M j, Y') }} – {{ $budget->period_end->format('M j, Y') }}</p></article>@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center text-sm text-slate-500 sm:col-span-2">No budgets configured.</div>@endforelse</section>
@if(app(\App\Shared\Authorization\ModuleAuthorizer::class)->allows('finance', \App\Finance\Enums\FinanceAbility::MANAGE_BUDGETS))<aside class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">Create budget</h2><form method="POST" action="{{ route('admin.finance.budgets.store') }}" class="mt-5 space-y-4" data-testid="finance-budget-form">@csrf
<div><label class="mb-1 block text-sm font-semibold">Name</label><input name="name" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div>
<div class="grid grid-cols-2 gap-3"><div><label class="mb-1 block text-sm font-semibold">Type</label><select name="type" class="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach(['event','department','category','project','team','vendor','campaign'] as $type)<option value="{{ $type }}">{{ ucfirst($type) }}</option>@endforeach</select></div><div><label class="mb-1 block text-sm font-semibold">Currency</label><input name="currency" value="{{ current_event_currency() }}" maxlength="3" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm uppercase"></div></div>
<div><label class="mb-1 block text-sm font-semibold">Expense category</label><select name="category_id" class="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">All categories</option>@foreach($categories as $category)<option value="{{ $category->id }}">{{ $category->name }}</option>@endforeach</select></div>
<div class="grid grid-cols-2 gap-3"><div><label class="mb-1 block text-sm font-semibold">Period start</label><input type="date" name="period_start" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div><div><label class="mb-1 block text-sm font-semibold">Period end</label><input type="date" name="period_end" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div></div>
<div class="grid grid-cols-2 gap-3"><div><label class="mb-1 block text-sm font-semibold">Planned income</label><input type="number" step="0.0001" min="0" name="planned_income" value="0" class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div><div><label class="mb-1 block text-sm font-semibold">Planned expense</label><input type="number" step="0.0001" min="0.0001" name="planned_expense" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div></div>
<div class="grid grid-cols-2 gap-3"><div><label class="mb-1 block text-sm font-semibold">Warning %</label><input type="number" name="warning_threshold" value="75" min="1" max="99" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div><div><label class="mb-1 block text-sm font-semibold">Critical %</label><input type="number" name="critical_threshold" value="90" min="2" max="100" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div></div><input type="hidden" name="status" value="active">
<button class="w-full rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white">Create budget</button></form></aside>@endif</div>
@endsection
