@extends('admin.layout')
@section('title', 'Finance Reconciliation')
@section('content')
<div class="mb-7"><p class="text-sm font-semibold uppercase tracking-[0.18em] text-indigo-600">Ledger assurance</p><h1 class="mt-1 text-3xl font-bold text-slate-950">Reconciliation</h1><p class="mt-2 text-sm text-slate-500">Import private statements, match ledger entries and resolve differences.</p></div>
@include('admin.finance._nav')
@if($errors->any())<div class="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700" role="alert"><p class="font-bold">{{ $errors->first() }}</p></div>@endif
<div class="grid gap-6 xl:grid-cols-3">
<section class="space-y-6 xl:col-span-2" data-testid="finance-reconciliation-list">
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold">Reconciliation periods</h2></div><div class="divide-y divide-slate-100">@forelse($reconciliations as $reconciliation)<a href="{{ route('admin.finance.reconciliation.show',$reconciliation) }}" class="flex items-center justify-between gap-4 px-5 py-4 hover:bg-slate-50"><div><p class="font-semibold">{{ $reconciliation->number }} · {{ $reconciliation->account?->name }}</p><p class="mt-1 text-xs text-slate-500">{{ $reconciliation->period_start->format('M j') }} – {{ $reconciliation->period_end->format('M j, Y') }}</p></div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold capitalize">{{ str_replace('_',' ',$reconciliation->status) }}</span></a>@empty<p class="px-5 py-10 text-center text-sm text-slate-500">No reconciliation periods.</p>@endforelse</div></div>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold">Statement imports</h2></div><div class="divide-y divide-slate-100">@forelse($imports as $import)<div class="flex items-center justify-between gap-4 px-5 py-4"><div><p class="font-semibold">{{ $import->original_filename }}</p><p class="mt-1 text-xs text-slate-500">{{ $import->account?->name }} · {{ $import->imported_count }} imported · {{ $import->duplicate_count }} duplicates</p></div><span class="text-xs font-semibold capitalize text-slate-600">{{ str_replace('_',' ',$import->status) }}</span></div>@empty<p class="px-5 py-10 text-center text-sm text-slate-500">No statements imported.</p>@endforelse</div></div>
<div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">Exchange rates</h2><div class="mt-4 grid gap-2 sm:grid-cols-2">@forelse($rates as $rate)<div class="flex items-center justify-between rounded-xl bg-slate-50 px-3.5 py-3 text-sm"><span class="font-semibold">{{ $rate->from_currency }} → {{ $rate->to_currency }}</span><span>{{ $rate->rate }} · {{ $rate->effective_date->format('M j') }}</span></div>@empty<p class="text-sm text-slate-500">No exchange rates.</p>@endforelse</div></div>
</section>
<aside class="space-y-5">
<details open class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary class="cursor-pointer font-bold">Start reconciliation</summary><form method="POST" action="{{ route('admin.finance.reconciliation.store') }}" class="mt-4 space-y-3" data-testid="finance-reconciliation-form">@csrf
<select name="account_id" required class="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }} · {{ $account->currency }}</option>@endforeach</select>
<div class="grid grid-cols-2 gap-2"><input type="date" name="period_start" required class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><input type="date" name="period_end" required class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div>
<div class="grid grid-cols-2 gap-2"><input type="number" step="0.0001" name="statement_opening_balance" required placeholder="Opening balance" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><input type="number" step="0.0001" name="statement_closing_balance" required placeholder="Closing balance" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></div><button class="w-full rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white">Start</button></form></details>
<details class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary class="cursor-pointer font-bold">Import statement CSV</summary><form method="POST" enctype="multipart/form-data" action="{{ route('admin.finance.reconciliation.imports.store') }}" class="mt-4 space-y-3" data-testid="finance-statement-form">@csrf
<select name="account_id" required class="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select><input type="file" name="statement" accept=".csv,text/csv" required class="w-full rounded-xl border border-dashed border-slate-300 p-3 text-sm"><p class="text-xs leading-5 text-slate-500">Required headers: date, description, and amount or debit/credit. Optional: reference, currency, balance.</p><button class="w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Import privately</button></form></details>
<details class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><summary class="cursor-pointer font-bold">Add exchange rate</summary><form method="POST" action="{{ route('admin.finance.reconciliation.rates.store') }}" class="mt-4 space-y-3" data-testid="finance-rate-form">@csrf
<div class="grid grid-cols-2 gap-2"><input name="from_currency" maxlength="3" required placeholder="From" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm uppercase"><input name="to_currency" maxlength="3" required placeholder="To" class="rounded-xl border border-slate-300 px-3 py-2.5 text-sm uppercase"></div><input type="number" step="0.00000001" min="0.00000001" name="rate" required placeholder="Rate" class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><input type="date" name="effective_date" value="{{ today()->toDateString() }}" required class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><input type="hidden" name="source" value="manual"><input name="override_reason" required placeholder="Rate source or reason" class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><button class="w-full rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white">Save rate</button></form></details>
</aside></div>
@endsection
