@extends('admin.layout')
@section('title', $reconciliation->number)
@section('content')
<div class="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><a href="{{ route('admin.finance.reconciliation.index') }}" class="text-sm font-semibold text-indigo-600">← Reconciliation</a><h1 class="mt-2 text-3xl font-bold text-slate-950">{{ $reconciliation->number }}</h1><p class="mt-2 text-sm text-slate-500">{{ $reconciliation->account->name }} · {{ $reconciliation->period_start->format('M j') }} – {{ $reconciliation->period_end->format('M j, Y') }}</p></div><div class="flex items-center gap-2"><span class="rounded-full bg-slate-100 px-3 py-2 text-xs font-bold capitalize">{{ str_replace('_',' ',$reconciliation->status) }}</span>@if($reconciliation->status !== 'completed')<form method="POST" action="{{ route('admin.finance.reconciliation.complete',$reconciliation) }}">@csrf<button class="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white">Complete reconciliation</button></form>@endif</div></div>
@if($errors->any())<div class="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700" role="alert">{{ $errors->first() }}</div>@endif
<section class="mb-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach([['Opening',$reconciliation->statement_opening_balance],['Statement closing',$reconciliation->statement_closing_balance],['Calculated closing',$reconciliation->calculated_closing_balance],['Difference',$reconciliation->difference_amount]] as [$label,$value])<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm font-semibold text-slate-500">{{ $label }}</p><p class="mt-3 text-xl font-bold">{{ $value !== null ? format_money($value,2,$reconciliation->currency) : '—' }}</p></article>@endforeach</section>
<div class="grid gap-6 xl:grid-cols-3"><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm xl:col-span-2" data-testid="finance-statement-entries"><div class="border-b border-slate-100 px-5 py-4"><h2 class="font-bold">Statement entries</h2></div><div class="divide-y divide-slate-100">@forelse($entries as $entry)<article class="p-5"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-semibold">{{ $entry->description }}</p><p class="mt-1 text-xs text-slate-500">{{ $entry->transaction_date->format('M j, Y') }} · {{ $entry->reference ?: 'No reference' }}</p></div><div class="text-left sm:text-right"><p class="font-bold {{ $entry->direction === 'incoming' ? 'text-emerald-600' : 'text-rose-600' }}">{{ $entry->direction === 'incoming' ? '+' : '−' }}{{ format_money($entry->amount,2,$entry->currency) }}</p><span class="text-xs font-semibold capitalize text-slate-500">{{ $entry->status }}</span></div></div>
@if($entry->status !== 'matched')<div class="mt-3 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-3"><form method="POST" action="{{ route('admin.finance.reconciliation.matches.suggest',[$reconciliation,$entry]) }}">@csrf<button class="rounded-lg bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700">Find matches</button></form>@foreach($entry->matches->where('status','suggested') as $match)<form method="POST" action="{{ route('admin.finance.reconciliation.matches.confirm',[$reconciliation,$match]) }}">@csrf<button class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold">Confirm {{ $match->transaction?->number }} · {{ $match->confidence_score }}%</button></form>@endforeach</div>@endif</article>@empty<p class="p-12 text-center text-sm text-slate-500">Import a statement for this account and period.</p>@endforelse</div><div class="p-4">{{ $entries->links() }}</div></section>
<aside class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-bold">Record adjustment</h2><p class="mt-1 text-xs text-slate-500">Adjustments create auditable ledger entries.</p><form method="POST" action="{{ route('admin.finance.reconciliation.adjustments.store',$reconciliation) }}" class="mt-5 space-y-3" data-testid="finance-adjustment-form">@csrf
<select name="type" required class="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm">@foreach(['bank_fee','currency_difference','rounding_difference','missing_transaction','duplicate_transaction','incorrect_amount','reversed_transaction'] as $type)<option value="{{ $type }}">{{ ucfirst(str_replace('_',' ',$type)) }}</option>@endforeach</select><select name="direction" required class="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm"><option value="outgoing">Outgoing</option><option value="incoming">Incoming</option></select><input type="number" step="0.0001" min="0.0001" name="amount" required placeholder="Amount" class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"><textarea name="reason" required rows="3" placeholder="Adjustment reason" class="w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm"></textarea><button class="w-full rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white">Record adjustment</button></form></aside></div>
@endsection
